### PR TITLE
Short UI Task

### PR DESCRIPTION
**Pull request by Rohit-110**
Issue: #191

### CODE REVIEW

**Comment by Rohit-110** [comment]
@rishika-g31 please request access for this

**Comment by rishika-g31** [comment]
sent

**Comment by Rohit-110** [comment]
@rishika-g31 done 👍

**Comment by Rohit-110** [comment]
@rishika-g31  we were not awarded points for this task, please check

**Comment by rishika-g31** [comment]
@Rohit-110 sorry for the inconvenience, you'll be awarded the points by today.

**Comment by Rohit-110** [comment]
@rishika-g31 points are still not awarded please check again

**Comment by rishika-g31** [comment]
@Rohit-110 awarded.

**Pull request merged**
