### PR TITLE
txt file added

### PR DESCRIPTION
**Pull request by Nandinig24**
Issue: #9

### CODE REVIEW

**Comment by rishika-g31** [comment]
Hey! you have not provided screenshot for the third law and you have also misinterpreted Hick's Law. Would suggest to go through the laws once more and make the necessary changes😊. keep contributing! 🚀

**Comment by Nandinig24** [comment]
What is last date of submission

**Comment by rishika-g31** [comment]
15th dec 11:59pm

**Comment by Nandinig24** [comment]
Issue: #9

**Comment by Nandinig24** [comment]
I had closed that pr and created new pr please merge it

**Pull request merged**
