### PR TITLE
Create parth_1egend.txt

### PR DESCRIPTION
**Pull request by parth1egend**
Issue: #1 

- Added FigJam link in .txt.
- No change suggested as of now.

### CODE REVIEW

**Comment by rishika-g31** [comment]
please provide your discord username.. Their's some discrepancy in your figma file.
Looks like you have directly copy pasted the user flow or generated it from AI.. as your version history is completely clean.
need to discuss on meet.

**Comment by parth1egend** [comment]
Discord User : parth_1egend
I am surprised by this. I have also submitted the flow chart in TechTerra Task.
I am new to Figma. I don't know the settings to keep while sharing or in which format should I open my file or proceed. I am watching tutorial and learning along the way. Maybe I shared the wrong file type making it unable for you to view the history( I don't even know if I can watch history).
Still I understand your concern , and I am ready to meet via discord .

**Comment by rishika-g31** [comment]
For the fair play it is important to judge every PR with transparency. Thank you for cooperating.

**Comment by rishika-g31** [comment]
join the meeting sharply by **9:20pm.**
your absence will lead to loss of points.

To join the video meeting, click this link: 
[https://meet.google.com/zst-dzfq-uyj ](url)

**Comment by parth1egend** [comment]
Sure!

**Pull request merged**
